# Generated by Django 5.0.2 on 2024-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='totalclasses',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
