# Generated by Django 5.0.2 on 2024-02-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_subject_absent_subject_present_subject_totalclasses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='absent',
        ),
    ]
